Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -130,44 +130,44 @@ jobs:
           name: coverage-html
           path: coverage.html
 
-      - name: Static Code Analysis
-        uses: sonarsource/sonarqube-scan-action@v2
-        with:
-          projectBaseDir: .
-          args: >
-            -Dsonar.organization=sonarintegration-1
-            -Dsonar.projectKey=sonarintegration-1_go-todo-project
-            -Dsonar.sources=./
-            -Dsonar.go.coverage.reportPaths=coverage.out
-            -Dsonar.host.url=https://sonarcloud.io
-            -Dsonar.pullrequest.provider=GitHub
-            -Dsonar.pullrequest.github.repository=${{ github.repository }}
-            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
-            -Dsonar.pullrequest.branch=${{ github.head_ref }}
-            -Dsonar.pullrequest.base=${{ github.base_ref }}
-        env:
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
+      # - name: Static Code Analysis
+      #   uses: sonarsource/sonarqube-scan-action@v2
+      #   with:
+      #     projectBaseDir: .
+      #     args: >
+      #       -Dsonar.organization=sonarintegration-1
+      #       -Dsonar.projectKey=sonarintegration-1_go-todo-project
+      #       -Dsonar.sources=./
+      #       -Dsonar.go.coverage.reportPaths=coverage.out
+      #       -Dsonar.host.url=https://sonarcloud.io
+      #       -Dsonar.pullrequest.provider=GitHub
+      #       -Dsonar.pullrequest.github.repository=${{ github.repository }}
+      #       -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
+      #       -Dsonar.pullrequest.branch=${{ github.head_ref }}
+      #       -Dsonar.pullrequest.base=${{ github.base_ref }}
+      #   env:
+      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+      #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
 
-      - name: Quality check for SonarCloud
-        env:
-          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-               curl -s https://sonarcloud.io/api/qualitygates/project_status?projectKey=${{ secrets.SONAR_PROJECT_KEY }} -o result.json
-               cat result.json
-               if [ "$(jq -r '.projectStatus.status' result.json)" = "ERROR" ]; then
-                  echo "Quality gate failed."
-                  exit 1
-               else
-                  echo "Quality gate passed."
-               fi
+      # - name: Quality check for SonarCloud
+      #   env:
+      #     SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
+      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      #   run: |
+      #          curl -s https://sonarcloud.io/api/qualitygates/project_status?projectKey=${{ secrets.SONAR_PROJECT_KEY }} -o result.json
+      #          cat result.json
+      #          if [ "$(jq -r '.projectStatus.status' result.json)" = "ERROR" ]; then
+      #             echo "Quality gate failed."
+      #             exit 1
+      #          else
+      #             echo "Quality gate passed."
+      #          fi
 
-               failedConditions=$(jq -r '.projectStatus.conditions[] | select(.status == "ERROR") | "\(.metricKey): \(.actualValue) (threshold: \(.errorThreshold))"' result.json)
-               if [ -n "$failedConditions" ]; then
-                 echo "Failed Conditions:"
-                 echo "$failedConditions"
-               fi
+      #          failedConditions=$(jq -r '.projectStatus.conditions[] | select(.status == "ERROR") | "\(.metricKey): \(.actualValue) (threshold: \(.errorThreshold))"' result.json)
+      #          if [ -n "$failedConditions" ]; then
+      #            echo "Failed Conditions:"
+      #            echo "$failedConditions"
+      #          fi
 
 
       # - name: Send notification on Slack using Webhooks - Success
